### ISSUE TITLE
get list of rest specifications

### ISSUE THREAD

**Issue by ctaggart** [ctaggart/autorust#35]
Get a list of specifications to generate code for from:
https://github.com/Azure/azure-rest-api-specs/tree/master/specification

I think this can be done by parsing the markdown in Rust. This library looked good to me when I looked:
https://crates.io/keywords/markdown
https://github.com/kivikakk/comrak

I think it is a matter of parsing the [readme.md](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/storage/resource-manager/readme.md) or [readme.azureresourceschema.md](
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/storage/resource-manager/readme.azureresourceschema.md) files

Each spec will have a list of input files. Hopefully we can also derive a Rust package name. I manually derived this name from the Python readme.
- [azure_mgmt_storage_v2019_06_01](https://github.com/ctaggart/azure-sdk-for-rust/tree/rest/rest/azure_mgmt_storage_v2019_06_01)

@guywaldman expressed interest in working on this.

**Comment by guywaldman** [comment]
Update on my end - will have a PR up by EOW.

**Comment by guywaldman** [comment]
#61 merged the initial CommonMark literate configuration parser.
