### ISSUE TITLE
other param named `configuration`

### ISSUE THREAD

**Issue by ctaggart** [ctaggart/autorust#65]
maintenance can't compile because another param is named config

``` rust
    pub async fn create_or_update(
        configuration: &crate::Configuration,
        subscription_id: &str,
        resource_group_name: &str,
        resource_name: &str,
        configuration: &MaintenanceConfiguration,
    ) -> std::result::Result<MaintenanceConfiguration, create_or_update::Error> {
```

May be`operation_config: OperationConfig`?

**Comment by rylev** [comment]
Choosing a different name isn't really solving the issue, it's just moving it around. Renaming the type to `OperationConfig` will break if there's ever another type named `OperationConfig`. I think instead we should come up with some way to unambiguously refer to the Configuration we mean. Right now we're using `use crate::*` which would make this difficult, but if we move away from that, we should be able to refer to the configuration in a way that is unambiguous.

**Comment by ctaggart** [comment]
@rylev, looks like I already removed `use crate::*` from `operations.rs`. I'll remove it from `models.rs`. The actual conflict above is the two parameters named `configuration`:
- `configuration: &crate::Configuration,`
- `configuration: &MaintenanceConfiguration,`

This will still break if a parameter is named `operationConfig`. Practically, however, there are none with that name currently and it is against the Azure spec guidelines to use abbreviations like `Config` in the specs.
