### ISSUE TITLE
Automatically box use of struct as a field in that struct

### ISSUE THREAD

**Issue by rylev** [ctaggart/autorust#85]
As hinted in #84, we should (when possible) automatically box types when they are used as the type of their own field. 

For example, it should be possible to detect the following situation:

```rust
struct Foo {
   bar: Bar,
   foo: Foo
}
```

and turn it into:

```rust
struct Foo {
   bar: Bar,
   foo: Box<Foo>
}
```

**Comment by ctaggart** [comment]
moved to https://github.com/Azure/azure-sdk-for-rust/issues/225
